try:
    n=3
    print(n)
    raise TypeError
except:
    print("exception raised")
